// OmniDrive Tools - Master Registry of all 105 Browser Utilities

export const CATEGORIES = [
  { id: 'pdf-tools', name: 'PDF & Documents', icon: 'pdf', color: '#5B5BD6', desc: 'Merge, split, compress, convert, sign and secure PDF documents completely in browser.' },
  { id: 'image-tools', name: 'Image Media', icon: 'image', color: '#12A88A', desc: 'Compress, resize, crop, filter, vector trace, convert formats and extract palettes.' },
  { id: 'video-audio-tools', name: 'Video & Audio', icon: 'video', color: '#D97706', desc: 'Client-side audio trimming, video mute, compression, transcription, and conversion.' },
  { id: 'security-dev-tools', name: 'Security & Developer', icon: 'code', color: '#4F46E5', desc: 'Bcrypt hashing, JWT debugger, regex tester, subnets, SHA hashes, formatters.' },
  { id: 'writing-text-tools', name: 'Writing & Text', icon: 'text', color: '#2563EB', desc: 'AI prompt engineer, word counter, slug generator, markdown tables, case converter.' },
  { id: 'finance-math-tools', name: 'Finance & Calculators', icon: 'calculator', color: '#059669', desc: 'DCA profit, SaaS MRR, freelance hourly rate, loan EMI, compound interest.' }
];

export const TOOLS = [
  // PDF TOOLS (30)
  { id: 'pdf-merge', name: 'PDF Merge', path: '/pdf-tools/merge', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Combine multiple PDF files into one ordered document entirely in your browser without file uploads.',
    keywords: ['merge pdf', 'combine pdf', 'join pdf'], tags: ['pdf', 'combine', 'documents'] },
  { id: 'pdf-split', name: 'PDF Split', path: '/pdf-tools/split', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Extract individual pages or custom page ranges into standalone PDF files instantly.',
    keywords: ['split pdf', 'extract pages', 'separate pdf'], tags: ['pdf', 'split', 'pages'] },
  { id: 'pdf-compress', name: 'PDF Compress', path: '/pdf-tools/compress', category: 'pdf-tools', icon: 'compress', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Optimize and reduce PDF document size locally without server-side compression.',
    keywords: ['compress pdf', 'reduce pdf size', 'shrink pdf'], tags: ['pdf', 'compress', 'optimize'] },
  { id: 'pdf-to-word', name: 'PDF to Word', path: '/pdf-tools/pdf-to-word', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'docx',
    desc: 'Convert PDF document text and structure into an editable Microsoft Word DOCX document.',
    keywords: ['pdf to word', 'pdf to docx', 'convert pdf to word'], tags: ['pdf', 'word', 'docx'] },
  { id: 'word-to-pdf', name: 'Word to PDF', path: '/pdf-tools/word-to-pdf', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.docx,.txt', output: 'pdf',
    desc: 'Render text and Word documents into standardized printable PDF format locally.',
    keywords: ['word to pdf', 'docx to pdf'], tags: ['word', 'pdf', 'convert'] },
  { id: 'pdf-to-excel', name: 'PDF to Excel', path: '/pdf-tools/pdf-to-excel', category: 'pdf-tools', icon: 'calculator', engine: 'pdfEngine', input: '.pdf', output: 'xlsx',
    desc: 'Extract tabular lines and data from PDF documents directly into a valid XLSX spreadsheet.',
    keywords: ['pdf to excel', 'pdf to xlsx', 'pdf spreadsheet'], tags: ['pdf', 'excel', 'data'] },
  { id: 'excel-to-pdf', name: 'Excel to PDF', path: '/pdf-tools/excel-to-pdf', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.xlsx,.xls,.csv', output: 'pdf',
    desc: 'Convert spreadsheet data worksheets into formatted printable PDF reports.',
    keywords: ['excel to pdf', 'xlsx to pdf', 'csv to pdf'], tags: ['excel', 'pdf', 'sheet'] },
  { id: 'pdf-to-ppt', name: 'PDF to PowerPoint', path: '/pdf-tools/pdf-to-ppt', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pptx',
    desc: 'Turn PDF pages into editable PowerPoint PPTX presentation slides.',
    keywords: ['pdf to ppt', 'pdf to powerpoint', 'pdf to pptx'], tags: ['pdf', 'presentation'] },
  { id: 'ppt-to-pdf', name: 'PowerPoint to PDF', path: '/pdf-tools/ppt-to-pdf', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pptx,.txt', output: 'pdf',
    desc: 'Package presentation slides and outline content into distribution-ready PDF documents.',
    keywords: ['ppt to pdf', 'powerpoint to pdf'], tags: ['presentation', 'pdf'] },
  { id: 'pdf-to-jpg', name: 'PDF to JPG', path: '/pdf-tools/pdf-to-jpg', category: 'pdf-tools', icon: 'image', engine: 'pdfEngine', input: '.pdf', output: 'jpg',
    desc: 'Render PDF document pages into high-resolution JPG images client-side.',
    keywords: ['pdf to jpg', 'pdf to jpeg', 'pdf pages to images'], tags: ['pdf', 'jpg', 'images'] },
  { id: 'jpg-to-pdf', name: 'JPG to PDF', path: '/pdf-tools/jpg-to-pdf', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.jpg,.jpeg', output: 'pdf',
    desc: 'Combine multiple JPG photographs or scans into a clean multi-page PDF.',
    keywords: ['jpg to pdf', 'images to pdf'], tags: ['jpg', 'pdf'] },
  { id: 'pdf-to-png', name: 'PDF to PNG', path: '/pdf-tools/pdf-to-png', category: 'pdf-tools', icon: 'image', engine: 'pdfEngine', input: '.pdf', output: 'png',
    desc: 'Export crisp transparent-capable PNG graphic images from PDF pages.',
    keywords: ['pdf to png', 'extract pdf png'], tags: ['pdf', 'png'] },
  { id: 'png-to-pdf', name: 'PNG to PDF', path: '/pdf-tools/png-to-pdf', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.png', output: 'pdf',
    desc: 'Convert transparent PNG graphics and artwork into standard PDF pages.',
    keywords: ['png to pdf', 'convert png'], tags: ['png', 'pdf'] },
  { id: 'pdf-to-text', name: 'PDF to Text', path: '/pdf-tools/pdf-to-text', category: 'pdf-tools', icon: 'text', engine: 'pdfEngine', input: '.pdf', output: 'txt',
    desc: 'Extract plain raw text from any readable PDF document preserving page order.',
    keywords: ['pdf to text', 'extract text pdf'], tags: ['pdf', 'text'] },
  { id: 'html-to-pdf', name: 'HTML to PDF', path: '/pdf-tools/html-to-pdf', category: 'pdf-tools', icon: 'code', engine: 'pdfEngine', input: '.html,.txt', output: 'pdf',
    desc: 'Render client-sanitized HTML and rich formatted text into downloadable PDF.',
    keywords: ['html to pdf', 'webpage to pdf'], tags: ['html', 'pdf'] },
  { id: 'protect-pdf', name: 'Protect PDF', path: '/pdf-tools/protect-pdf', category: 'pdf-tools', icon: 'lock', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Encrypt your PDF with client-side user and owner security passwords.',
    keywords: ['protect pdf', 'encrypt pdf', 'password protect pdf'], tags: ['pdf', 'security'] },
  { id: 'unlock-pdf', name: 'Unlock PDF', path: '/pdf-tools/unlock-pdf', category: 'pdf-tools', icon: 'unlock', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Decrypt protected PDFs using your valid password to produce an unlocked copy.',
    keywords: ['unlock pdf', 'remove pdf password'], tags: ['pdf', 'security'] },
  { id: 'add-watermark', name: 'Add Watermark to PDF', path: '/pdf-tools/add-watermark', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Overlay customizable text watermarks across PDF pages with angle and opacity controls.',
    keywords: ['watermark pdf', 'stamp pdf'], tags: ['pdf', 'watermark'] },
  { id: 'remove-watermark', name: 'Remove Watermark from PDF', path: '/pdf-tools/remove-watermark', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Inspect and strip recognized text watermark artifact layers from PDF structure.',
    keywords: ['remove watermark pdf', 'clean pdf'], tags: ['pdf', 'watermark'] },
  { id: 'sign-pdf', name: 'Sign PDF', path: '/pdf-tools/sign-pdf', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Draw or type your signature and visually stamp it onto any page of a PDF.',
    keywords: ['sign pdf', 'signature on pdf'], tags: ['pdf', 'signature'] },
  { id: 'rotate-pdf', name: 'Rotate PDF', path: '/pdf-tools/rotate-pdf', category: 'pdf-tools', icon: 'rotate', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Rotate individual pages or all pages of a PDF by 90, 180, or 270 degrees.',
    keywords: ['rotate pdf', 'turn pdf pages'], tags: ['pdf', 'rotate'] },
  { id: 'crop-pdf', name: 'Crop PDF', path: '/pdf-tools/crop-pdf', category: 'pdf-tools', icon: 'crop', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Trim page margins and adjust bounding crop boxes across your PDF documents.',
    keywords: ['crop pdf', 'trim pdf margins'], tags: ['pdf', 'crop'] },
  { id: 'extract-pdf-images', name: 'Extract PDF Images', path: '/pdf-tools/extract-pdf-images', category: 'pdf-tools', icon: 'image', engine: 'pdfEngine', input: '.pdf', output: 'images',
    desc: 'Extract embedded raster images and figures from inside your PDF files.',
    keywords: ['extract pdf images', 'get images from pdf'], tags: ['pdf', 'images'] },
  { id: 'remove-pdf-pages', name: 'Remove PDF Pages', path: '/pdf-tools/remove-pdf-pages', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Select and delete unwanted pages from your PDF file without server transfer.',
    keywords: ['remove pdf pages', 'delete pages from pdf'], tags: ['pdf', 'pages'] },
  { id: 'reorder-pdf-pages', name: 'Reorder PDF Pages', path: '/pdf-tools/reorder-pdf-pages', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Rearrange and resequence pages in any order using a drag-and-drop workspace.',
    keywords: ['reorder pdf pages', 'rearrange pdf'], tags: ['pdf', 'organize'] },
  { id: 'add-page-numbers', name: 'Add Page Numbers to PDF', path: '/pdf-tools/add-page-numbers', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.pdf', output: 'pdf',
    desc: 'Stamp custom formatted page numbers (e.g. Page X of Y) onto any position in your PDF.',
    keywords: ['number pdf pages', 'page numbers pdf'], tags: ['pdf', 'numbering'] },
  { id: 'pdf-to-webp', name: 'PDF to WebP', path: '/pdf-tools/pdf-to-webp', category: 'pdf-tools', icon: 'image', engine: 'pdfEngine', input: '.pdf', output: 'webp',
    desc: 'Render document pages directly into modern lightweight WebP raster images.',
    keywords: ['pdf to webp', 'convert pdf webp'], tags: ['pdf', 'webp'] },
  { id: 'webp-to-pdf', name: 'WebP to PDF', path: '/pdf-tools/webp-to-pdf', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.webp', output: 'pdf',
    desc: 'Combine modern WebP image assets into a cohesive multi-page PDF.',
    keywords: ['webp to pdf', 'convert webp to pdf'], tags: ['webp', 'pdf'] },
  { id: 'epub-to-pdf', name: 'EPUB to PDF', path: '/pdf-tools/epub-to-pdf', category: 'pdf-tools', icon: 'pdf', engine: 'pdfEngine', input: '.epub', output: 'pdf',
    desc: 'Parse EPUB ebook chapters and render book contents into printable PDF.',
    keywords: ['epub to pdf', 'ebook to pdf'], tags: ['epub', 'pdf', 'ebook'] },
  { id: 'pdf-to-epub', name: 'PDF to EPUB', path: '/pdf-tools/pdf-to-epub', category: 'pdf-tools', icon: 'text', engine: 'pdfEngine', input: '.pdf', output: 'epub',
    desc: 'Convert PDF document chapters and text into an EPUB digital reader ebook.',
    keywords: ['pdf to epub', 'pdf to ebook'], tags: ['pdf', 'epub', 'ebook'] },

  // IMAGE TOOLS (25)
  { id: 'img-compressor', name: 'Image Compressor', path: '/image-tools/compressor', category: 'image-tools', icon: 'compress', engine: 'imageEngine', input: 'image/*', output: 'image',
    desc: 'Compress JPG, PNG, and WebP images with adjustable quality and instant size preview.',
    keywords: ['compress image', 'shrink photo', 'reduce image size'], tags: ['image', 'compress'] },
  { id: 'img-resizer', name: 'Image Resizer', path: '/image-tools/resizer', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'image',
    desc: 'Resize image dimensions by percentage or pixel values with aspect ratio lock.',
    keywords: ['resize image', 'image dimensions', 'scale photo'], tags: ['image', 'resize'] },
  { id: 'img-cropper', name: 'Image Cropper', path: '/image-tools/cropper', category: 'image-tools', icon: 'crop', engine: 'imageEngine', input: 'image/*', output: 'image',
    desc: 'Crop photographs to custom ratios (1:1, 16:9, 4:3) with precise interactive bounds.',
    keywords: ['crop image', 'cut photo', 'crop tool'], tags: ['image', 'crop'] },
  { id: 'img-webp-converter', name: 'WebP Converter', path: '/image-tools/webp-converter', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'webp',
    desc: 'Convert any image format into ultra-compressed, web-optimized WebP files.',
    keywords: ['webp converter', 'convert to webp'], tags: ['image', 'webp'] },
  { id: 'img-png-to-jpg', name: 'PNG to JPG', path: '/image-tools/png-to-jpg', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: '.png', output: 'jpg',
    desc: 'Convert transparent PNG files into high-density JPG with customizable background color.',
    keywords: ['png to jpg', 'convert png to jpeg'], tags: ['png', 'jpg'] },
  { id: 'img-jpg-to-png', name: 'JPG to PNG', path: '/image-tools/jpg-to-png', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: '.jpg,.jpeg', output: 'png',
    desc: 'Transform JPG compressed pictures into lossless PNG format client-side.',
    keywords: ['jpg to png', 'jpeg to png'], tags: ['jpg', 'png'] },
  { id: 'img-svg-to-png', name: 'SVG to PNG', path: '/image-tools/svg-to-png', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: '.svg', output: 'png',
    desc: 'Render vector SVG graphics into crisp raster PNG images at any desired scale.',
    keywords: ['svg to png', 'render svg'], tags: ['svg', 'png'] },
  { id: 'img-png-to-svg', name: 'PNG to SVG (Vector Tracing)', path: '/image-tools/png-to-svg', category: 'image-tools', icon: 'code', engine: 'imageEngine', input: '.png,.jpg', output: 'svg',
    desc: 'Trace raster pixel outlines into genuine vector SVG bezier paths.',
    keywords: ['png to svg', 'vectorize image', 'image tracer'], tags: ['png', 'svg', 'vector'] },
  { id: 'img-background-remover', name: 'Background Remover', path: '/image-tools/background-remover', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'png',
    desc: 'Detect and remove solid backgrounds or chroma colors directly in browser canvas.',
    keywords: ['remove background', 'transparent background'], tags: ['image', 'transparency'] },
  { id: 'img-color-palette-extractor', name: 'Color Palette Extractor', path: '/image-tools/color-palette-extractor', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'palette',
    desc: 'Analyze photograph pixels to generate HEX and RGB color swatches.',
    keywords: ['extract color palette', 'image color picker'], tags: ['image', 'colors'] },
  { id: 'img-svg-editor', name: 'SVG Code Editor & Previewer', path: '/image-tools/svg-editor', category: 'image-tools', icon: 'code', engine: 'imageEngine', input: '.svg,text', output: 'svg',
    desc: 'Interactive SVG code editor with live viewport inspection and optimized export.',
    keywords: ['svg editor', 'edit svg', 'preview svg'], tags: ['svg', 'vector'] },
  { id: 'img-photo-filters', name: 'Photo Filters & Adjustments', path: '/image-tools/photo-filters', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'image',
    desc: 'Apply brightness, contrast, grayscale, sepia, invert, and saturation adjustments.',
    keywords: ['photo filters', 'image adjustments', 'sepia filter'], tags: ['image', 'filter'] },
  { id: 'img-qr-code-generator', name: 'QR Code Generator', path: '/image-tools/qr-code-generator', category: 'image-tools', icon: 'code', engine: 'imageEngine', input: 'text', output: 'png',
    desc: 'Generate custom QR codes for URLs, WiFi credentials, vCards, and plain text.',
    keywords: ['qr code generator', 'make qr code'], tags: ['qr', 'generator'] },
  { id: 'img-qr-code-scanner', name: 'QR Code Scanner', path: '/image-tools/qr-code-scanner', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*,camera', output: 'text',
    desc: 'Scan QR codes from image uploads or live camera feed without sending frames to a server.',
    keywords: ['qr scanner', 'read qr code'], tags: ['qr', 'scanner'] },
  { id: 'img-barcode-generator', name: 'Barcode Generator', path: '/image-tools/barcode-generator', category: 'image-tools', icon: 'code', engine: 'imageEngine', input: 'text', output: 'svg',
    desc: 'Generate Code128, EAN-13, and UPC barcodes with instant SVG/PNG download.',
    keywords: ['barcode generator', 'make barcode', 'code128'], tags: ['barcode'] },
  { id: 'img-favicon-generator', name: 'Favicon Generator', path: '/image-tools/favicon-generator', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'zip',
    desc: 'Generate a complete suite of standard favicon icons (16x16, 32x32, 180x180, 512x512).',
    keywords: ['favicon generator', 'create favicon', 'apple touch icon'], tags: ['favicon', 'icon'] },
  { id: 'img-meme-generator', name: 'Meme Generator', path: '/image-tools/meme-generator', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'png',
    desc: 'Add top and bottom caption text overlays with classic Impact outline styling.',
    keywords: ['meme generator', 'make a meme'], tags: ['meme', 'fun'] },
  { id: 'img-image-to-text-ocr', name: 'Image-to-Text OCR', path: '/image-tools/image-to-text-ocr', category: 'image-tools', icon: 'text', engine: 'imageEngine', input: 'image/*', output: 'txt',
    desc: 'Extract printed text from scans and photographs using client-side OCR recognition.',
    keywords: ['image to text', 'ocr online', 'extract text from photo'], tags: ['ocr', 'text'] },
  { id: 'img-image-resizer-by-pixel', name: 'Image Resizer by Exact Pixels', path: '/image-tools/image-resizer-by-pixel', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'image',
    desc: 'Resize images to strict pixel targets with bicubic smoothing.',
    keywords: ['pixel resizer', 'exact image size'], tags: ['resize', 'pixels'] },
  { id: 'img-image-enlarger', name: 'Image Enlarger (Upscaler)', path: '/image-tools/image-enlarger', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'image',
    desc: 'Enlarge graphics 2x or 4x using high-quality canvas interpolation (smooth resize, not AI upscaling).',
    keywords: ['enlarge image', 'upscale photo'], tags: ['upscale', 'image'] },
  { id: 'img-gif-to-mp4', name: 'GIF to MP4 Converter', path: '/image-tools/gif-to-mp4', category: 'image-tools', icon: 'video', engine: 'imageEngine', input: '.gif', output: 'mp4',
    desc: 'Convert animated GIFs into compact video (saved as MP4 where your browser supports it, otherwise WebM).',
    keywords: ['gif to mp4', 'convert gif video'], tags: ['gif', 'mp4'] },
  { id: 'img-mp4-to-gif', name: 'MP4 to GIF Maker', path: '/image-tools/mp4-to-gif', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: '.mp4,.webm', output: 'gif',
    desc: 'Sample video frames to generate animated looping GIFs directly in browser.',
    keywords: ['mp4 to gif', 'video to gif'], tags: ['video', 'gif'] },
  { id: 'img-image-metadata-exif-viewer', name: 'Image EXIF Metadata Viewer', path: '/image-tools/image-metadata-exif-viewer', category: 'image-tools', icon: 'info', engine: 'imageEngine', input: 'image/*', output: 'data',
    desc: 'Read camera model, focal length, ISO, exposure, and GPS tags from JPEG headers.',
    keywords: ['exif viewer', 'image metadata', 'photo info'], tags: ['exif', 'metadata'] },
  { id: 'img-blur-image', name: 'Blur Image Privacy Tool', path: '/image-tools/blur-image', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'image',
    desc: 'Apply Gaussian privacy blur filters to whole photos or sensitive regions.',
    keywords: ['blur image', 'blur photo', 'privacy blur'], tags: ['blur', 'privacy'] },
  { id: 'img-pixelate-image', name: 'Pixelate Image Censor', path: '/image-tools/pixelate-image', category: 'image-tools', icon: 'image', engine: 'imageEngine', input: 'image/*', output: 'image',
    desc: 'Censor sensitive information with classic mosaic pixelation blocks.',
    keywords: ['pixelate image', 'censor photo'], tags: ['pixelate', 'censor'] },

  // VIDEO & AUDIO TOOLS (15)
  { id: 'av-video-to-audio-mp3', name: 'Video to Audio MP3', path: '/video-audio-tools/video-to-audio-mp3', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: 'video/*', output: 'wav',
    desc: 'Extract the audio soundtrack from MP4, WebM, and MOV videos and save it as a lossless WAV file.',
    keywords: ['video to mp3', 'extract audio from video'], tags: ['video', 'audio', 'mp3'] },
  { id: 'av-audio-cutter-trimmer', name: 'Audio Cutter & Trimmer', path: '/video-audio-tools/audio-cutter-trimmer', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: 'audio/*', output: 'wav',
    desc: 'Cut, trim, and slice audio tracks with waveform start and end point markers.',
    keywords: ['audio cutter', 'trim audio', 'ringtone maker'], tags: ['audio', 'trim'] },
  { id: 'av-video-cutter-trimmer', name: 'Video Cutter & Trimmer', path: '/video-audio-tools/video-cutter-trimmer', category: 'video-audio-tools', icon: 'video', engine: 'ffmpegEngine', input: 'video/*', output: 'mp4',
    desc: 'Trim video clips to exact start and end timestamps in browser canvas.',
    keywords: ['video cutter', 'trim video', 'cut mp4'], tags: ['video', 'trim'] },
  { id: 'av-audio-format-converter', name: 'Audio Format Converter', path: '/video-audio-tools/audio-format-converter', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: 'audio/*', output: 'wav',
    desc: 'Convert audio files between WAV, MP3, and OGG formats cleanly.',
    keywords: ['audio converter', 'convert sound'], tags: ['audio', 'converter'] },
  { id: 'av-audio-merger', name: 'Audio Merger & Combiner', path: '/video-audio-tools/audio-merger', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: 'audio/*', output: 'wav',
    desc: 'Combine multiple voice notes and audio recordings into a continuous track.',
    keywords: ['audio merger', 'combine audio songs'], tags: ['audio', 'merge'] },
  { id: 'av-video-compressor', name: 'Video Compressor', path: '/video-audio-tools/video-compressor', category: 'video-audio-tools', icon: 'compress', engine: 'ffmpegEngine', input: 'video/*', output: 'mp4',
    desc: 'Reduce video file weight using client-side bitrate and canvas resolution re-encoding.',
    keywords: ['compress video', 'reduce video size'], tags: ['video', 'compress'] },
  { id: 'av-playback-speed-changer', name: 'Audio Playback Speed Changer', path: '/video-audio-tools/playback-speed-changer', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: 'audio/*', output: 'wav',
    desc: 'Speed up (1.25x, 1.5x, 2x) or slow down audio recordings without chipmunk effect.',
    keywords: ['audio speed', 'change playback speed', 'slow down audio'], tags: ['audio', 'speed'] },
  { id: 'av-srt-subtitle-generator', name: 'SRT Subtitle Generator', path: '/video-audio-tools/srt-subtitle-generator', category: 'video-audio-tools', icon: 'text', engine: 'ffmpegEngine', input: 'text', output: 'srt',
    desc: 'Compose and synchronize timed SRT subtitle files with timecode validation.',
    keywords: ['srt generator', 'make subtitles', 'caption creator'], tags: ['subtitles', 'srt'] },
  { id: 'av-browser-voice-recorder', name: 'Browser Voice Recorder', path: '/video-audio-tools/browser-voice-recorder', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: 'microphone', output: 'webm',
    desc: 'Record audio directly from your microphone with instant local download.',
    keywords: ['voice recorder', 'record microphone'], tags: ['record', 'audio'] },
  { id: 'av-audio-transcriber', name: 'Browser Audio Transcriber', path: '/video-audio-tools/audio-transcriber', category: 'video-audio-tools', icon: 'text', engine: 'ffmpegEngine', input: 'audio/*,mic', output: 'txt',
    desc: 'Transcribe spoken audio into text using local Web Speech Recognition.',
    keywords: ['audio transcriber', 'speech to text'], tags: ['speech', 'transcribe'] },
  { id: 'av-video-mute-utility', name: 'Video Mute Utility', path: '/video-audio-tools/video-mute-utility', category: 'video-audio-tools', icon: 'video', engine: 'ffmpegEngine', input: 'video/*', output: 'mp4',
    desc: 'Strip the audio track from video files cleanly to produce silent video clips.',
    keywords: ['mute video', 'remove audio from video'], tags: ['video', 'mute'] },
  { id: 'av-audio-volume-booster', name: 'Audio Volume Booster', path: '/video-audio-tools/audio-volume-booster', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: 'audio/*', output: 'wav',
    desc: 'Boost quiet audio recordings up to 300% volume with soft peak limiting.',
    keywords: ['volume booster', 'make audio louder'], tags: ['audio', 'volume'] },
  { id: 'av-mp3-metadata-editor', name: 'MP3 Metadata Tag Editor', path: '/video-audio-tools/mp3-metadata-editor', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: '.mp3', output: 'mp3',
    desc: 'Inspect and edit MP3 ID3 tags including Title, Artist, Album, and Year.',
    keywords: ['id3 editor', 'edit mp3 tags'], tags: ['mp3', 'metadata'] },
  { id: 'av-video-resizer-dimensions', name: 'Video Dimension Resizer', path: '/video-audio-tools/video-resizer-dimensions', category: 'video-audio-tools', icon: 'video', engine: 'ffmpegEngine', input: 'video/*', output: 'mp4',
    desc: 'Resize video dimensions to 720p, 1080p, square 1:1, or vertical 9:16.',
    keywords: ['resize video', 'video resolution changer'], tags: ['video', 'resize'] },
  { id: 'av-audio-reverse-tool', name: 'Audio Reverse Tool', path: '/video-audio-tools/audio-reverse-tool', category: 'video-audio-tools', icon: 'audio', engine: 'ffmpegEngine', input: 'audio/*', output: 'wav',
    desc: 'Play and export any sound file backwards using sample buffer reversal.',
    keywords: ['reverse audio', 'backwards sound'], tags: ['audio', 'reverse'] },

  // SECURITY & DEVELOPER TOOLS (15)
  { id: 'sec-password-strength-entropy-meter', name: 'Password Strength & Entropy Meter', path: '/security-dev-tools/password-strength-entropy-meter', category: 'security-dev-tools', icon: 'security', engine: 'cryptoEngine', input: 'text', output: 'analysis',
    desc: 'Calculate Shannon entropy bits, character pool diversity, and crack time estimates.',
    keywords: ['password strength', 'entropy calculator'], tags: ['security', 'password'] },
  { id: 'sec-bcrypt-password-hasher', name: 'Bcrypt Password Hasher & Verifier', path: '/security-dev-tools/bcrypt-password-hasher', category: 'security-dev-tools', icon: 'security', engine: 'cryptoEngine', input: 'text', output: 'hash',
    desc: 'Generate cryptographic bcrypt salted hashes with configurable rounds (4–14) locally.',
    keywords: ['bcrypt generator', 'hash password'], tags: ['bcrypt', 'security'] },
  { id: 'sec-md5-sha256-sha512-hash-generator', name: 'MD5, SHA-256 & SHA-512 Hash Generator', path: '/security-dev-tools/md5-sha256-sha512-hash-generator', category: 'security-dev-tools', icon: 'security', engine: 'cryptoEngine', input: 'text,file', output: 'hashes',
    desc: 'Compute cryptographic checksums for text or files using standard Web Crypto.',
    keywords: ['sha256 generator', 'md5 hash', 'checksum'], tags: ['hash', 'crypto'] },
  { id: 'sec-jwt-token-debugger', name: 'JWT Token Debugger & Verifier', path: '/security-dev-tools/jwt-token-debugger', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'jwt', output: 'json',
    desc: 'Decode JWT Header and Claims, verify HMAC signatures, and check token expiry.',
    keywords: ['jwt debugger', 'decode jwt', 'json web token'], tags: ['jwt', 'developer'] },
  { id: 'sec-base64-encoder-decoder', name: 'Base64 Encoder & Decoder', path: '/security-dev-tools/base64-encoder-decoder', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'text', output: 'text',
    desc: 'Encode and decode UTF-8 text and binary data into standard or URL-safe Base64.',
    keywords: ['base64 encode', 'base64 decode'], tags: ['base64', 'developer'] },
  { id: 'sec-json-formatter-validator', name: 'JSON Formatter & Validator', path: '/security-dev-tools/json-formatter-validator', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'json', output: 'json',
    desc: 'Beautify, minify, and validate JSON data with exact syntax error highlighting.',
    keywords: ['json formatter', 'validate json', 'beautify json'], tags: ['json', 'formatter'] },
  { id: 'sec-regex-tester-visualizer', name: 'Regex Tester & Match Visualizer', path: '/security-dev-tools/regex-tester-visualizer', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'regex', output: 'matches',
    desc: 'Test regular expressions in real-time with capture groups and regex flags.',
    keywords: ['regex tester', 'regular expression test'], tags: ['regex', 'developer'] },
  { id: 'sec-ip-subnet-calculator', name: 'IPv4 Subnet & CIDR Calculator', path: '/security-dev-tools/ip-subnet-calculator', category: 'security-dev-tools', icon: 'calculator', engine: 'cryptoEngine', input: 'ip', output: 'subnet',
    desc: 'Calculate network address, broadcast address, netmask, wildcard, and usable host count.',
    keywords: ['subnet calculator', 'cidr calculator'], tags: ['networking', 'ip'] },
  { id: 'sec-automatic-meta-tag-generator', name: 'SEO & Social Meta Tag Generator', path: '/security-dev-tools/automatic-meta-tag-generator', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'form', output: 'html',
    desc: 'Generate OpenGraph, Twitter Cards, and search engine meta tags with preview.',
    keywords: ['meta tag generator', 'opengraph tags'], tags: ['seo', 'meta'] },
  { id: 'sec-text-diff-checker', name: 'Text Diff Checker', path: '/security-dev-tools/text-diff-checker', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'text', output: 'diff',
    desc: 'Compare two text snippets side-by-side highlighting additions and deletions.',
    keywords: ['diff checker', 'compare text', 'text difference'], tags: ['diff', 'text'] },
  { id: 'sec-url-encoder-decoder', name: 'URL Encoder & Decoder', path: '/security-dev-tools/url-encoder-decoder', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'text', output: 'text',
    desc: 'Encode query parameters and decode percent-encoded RFC 3986 URLs.',
    keywords: ['url encode', 'percent encoding'], tags: ['url', 'developer'] },
  { id: 'sec-html-entity-converter', name: 'HTML Entity Encoder & Decoder', path: '/security-dev-tools/html-entity-converter', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'text', output: 'text',
    desc: 'Convert special symbols to named or numerical HTML entities and back.',
    keywords: ['html entities', 'escape html'], tags: ['html', 'entities'] },
  { id: 'sec-xml-to-json-converter', name: 'XML to JSON Converter', path: '/security-dev-tools/xml-to-json-converter', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'xml', output: 'json',
    desc: 'Parse XML document trees into clean JavaScript Object Notation data.',
    keywords: ['xml to json', 'convert xml'], tags: ['xml', 'json'] },
  { id: 'sec-json-to-xml-converter', name: 'JSON to XML Converter', path: '/security-dev-tools/json-to-xml-converter', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'json', output: 'xml',
    desc: 'Convert JSON structures into valid XML documents with configurable root nodes.',
    keywords: ['json to xml', 'convert json to xml'], tags: ['json', 'xml'] },
  { id: 'sec-hex-to-rgb-color-converter', name: 'HEX to RGB Color Converter', path: '/security-dev-tools/hex-to-rgb-color-converter', category: 'security-dev-tools', icon: 'code', engine: 'cryptoEngine', input: 'color', output: 'color',
    desc: 'Convert HEX, RGB, HSL, and CMYK color codes with interactive picker.',
    keywords: ['hex to rgb', 'rgb to hex', 'color converter'], tags: ['color', 'hex'] },

  // WRITING & TEXT TOOLS (10)
  { id: 'txt-ai-prompt-engineer-builder', name: 'AI Prompt Engineer Builder', path: '/writing-text-tools/ai-prompt-engineer-builder', category: 'writing-text-tools', icon: 'writing', engine: 'textEngine', input: 'form', output: 'prompt',
    desc: 'Construct structured production prompts with role, context, constraints, and few-shots.',
    keywords: ['prompt builder', 'ai prompt engineer'], tags: ['prompt', 'ai', 'writing'] },
  { id: 'txt-advanced-word-counter', name: 'Advanced Word Counter & Readability', path: '/writing-text-tools/advanced-word-counter', category: 'writing-text-tools', icon: 'text', engine: 'textEngine', input: 'text', output: 'stats',
    desc: 'Real-time count of words, characters, sentences, reading time, and speaking time.',
    keywords: ['word counter', 'character count', 'reading time'], tags: ['writing', 'stats'] },
  { id: 'txt-text-case-converter', name: 'Text Case Converter', path: '/writing-text-tools/text-case-converter', category: 'writing-text-tools', icon: 'text', engine: 'textEngine', input: 'text', output: 'text',
    desc: 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, and kebab-case.',
    keywords: ['case converter', 'title case', 'camelcase'], tags: ['text', 'case'] },
  { id: 'txt-website-slug-url-generator', name: 'Website Slug URL Generator', path: '/writing-text-tools/website-slug-url-generator', category: 'writing-text-tools', icon: 'text', engine: 'textEngine', input: 'text', output: 'slug',
    desc: 'Transform article titles into clean, URL-safe SEO slugs with custom delimiters.',
    keywords: ['slug generator', 'url slug maker'], tags: ['slug', 'seo'] },
  { id: 'txt-lorem-ipsum-dummy-generator', name: 'Lorem Ipsum Dummy Text Generator', path: '/writing-text-tools/lorem-ipsum-dummy-generator', category: 'writing-text-tools', icon: 'text', engine: 'textEngine', input: 'form', output: 'text',
    desc: 'Generate standard Latin placeholder dummy copy by paragraphs, sentences, or words.',
    keywords: ['lorem ipsum', 'dummy text generator'], tags: ['lorem', 'placeholder'] },
  { id: 'txt-find-and-replace-text-processor', name: 'Find and Replace Text Processor', path: '/writing-text-tools/find-and-replace-text-processor', category: 'writing-text-tools', icon: 'text', engine: 'textEngine', input: 'text', output: 'text',
    desc: 'Batch replace words or regex patterns with match counters and case-sensitivity.',
    keywords: ['find and replace', 'replace text'], tags: ['replace', 'text'] },
  { id: 'txt-markdown-table-generator', name: 'Markdown Table Generator', path: '/writing-text-tools/markdown-table-generator', category: 'writing-text-tools', icon: 'code', engine: 'textEngine', input: 'grid', output: 'markdown',
    desc: 'Visual spreadsheet grid editor that exports formatted GitHub Markdown tables.',
    keywords: ['markdown table', 'make markdown table'], tags: ['markdown', 'table'] },
  { id: 'txt-binary-to-text-converter', name: 'Binary to Text Converter', path: '/writing-text-tools/binary-to-text-converter', category: 'writing-text-tools', icon: 'code', engine: 'textEngine', input: 'binary', output: 'text',
    desc: 'Translate 8-bit binary 0s and 1s into ASCII and UTF-8 plain text.',
    keywords: ['binary to text', 'decode binary'], tags: ['binary', 'text'] },
  { id: 'txt-text-to-binary-converter', name: 'Text to Binary Converter', path: '/writing-text-tools/text-to-binary-converter', category: 'writing-text-tools', icon: 'code', engine: 'textEngine', input: 'text', output: 'binary',
    desc: 'Encode plain text strings into space-separated binary byte representations.',
    keywords: ['text to binary', 'encode binary'], tags: ['binary', 'encoding'] },
  { id: 'txt-string-reverse-utility', name: 'String Reverse Utility', path: '/writing-text-tools/string-reverse-utility', category: 'writing-text-tools', icon: 'text', engine: 'textEngine', input: 'text', output: 'text',
    desc: 'Reverse strings by character or word order with Unicode grapheme support.',
    keywords: ['reverse string', 'backwards text'], tags: ['reverse', 'text'] },

  // FINANCE & MATH TOOLS (10)
  { id: 'fin-crypto-dca-profit-calculator', name: 'Crypto DCA Profit Calculator', path: '/finance-math-tools/crypto-dca-profit-calculator', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'roi',
    desc: 'Calculate Dollar Cost Averaging returns, average purchase price, and cumulative ROI.',
    keywords: ['dca calculator', 'crypto profit calculator'], tags: ['crypto', 'dca', 'finance'] },
  { id: 'fin-saas-mrr-churn-pricing-calculator', name: 'SaaS MRR & Churn Calculator', path: '/finance-math-tools/saas-mrr-churn-pricing-calculator', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'metrics',
    desc: 'Model Monthly Recurring Revenue (MRR), ARR, logo churn, ARPU, and Customer Lifetime Value.',
    keywords: ['saas calculator', 'mrr calculator', 'churn rate'], tags: ['saas', 'mrr', 'business'] },
  { id: 'fin-freelance-hourly-rate-calculator', name: 'Freelance Hourly Rate Calculator', path: '/finance-math-tools/freelance-hourly-rate-calculator', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'rate',
    desc: 'Compute your target billable hourly rate based on personal expenses and overhead.',
    keywords: ['freelance rate calculator', 'hourly rate'], tags: ['freelance', 'rate', 'income'] },
  { id: 'fin-compound-interest-wealth-projection', name: 'Compound Interest Wealth Projection', path: '/finance-math-tools/compound-interest-wealth-projection', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'projection',
    desc: 'Simulate investment growth with compound frequency and recurring monthly deposits.',
    keywords: ['compound interest calculator', 'investment projection'], tags: ['investing', 'interest'] },
  { id: 'fin-ecom-profit-margin-roi-calculator', name: 'E-Commerce Profit Margin & ROI', path: '/finance-math-tools/ecom-profit-margin-roi-calculator', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'margin',
    desc: 'Calculate gross margins, net margins, marketplace commissions, and break-even ROAS.',
    keywords: ['ecommerce calculator', 'profit margin calculator', 'roas'], tags: ['ecommerce', 'margin'] },
  { id: 'fin-global-sales-tax-vat-calculator', name: 'Global Sales Tax & VAT Calculator', path: '/finance-math-tools/global-sales-tax-vat-calculator', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'tax',
    desc: 'Compute inclusive and exclusive tax amounts across standard national VAT and GST rates.',
    keywords: ['vat calculator', 'sales tax calculator', 'gst'], tags: ['vat', 'tax'] },
  { id: 'fin-fiat-currency-inflation-calculator', name: 'Fiat Currency Inflation Calculator', path: '/finance-math-tools/fiat-currency-inflation-calculator', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'inflation',
    desc: 'Calculate historical purchasing power depreciation and cumulative inflation impact.',
    keywords: ['inflation calculator', 'purchasing power'], tags: ['inflation', 'currency'] },
  { id: 'fin-digital-asset-valuation-calculator', name: 'Digital Asset Valuation Calculator', path: '/finance-math-tools/digital-asset-valuation-calculator', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'valuation',
    desc: 'Estimate website, newsletter, and SaaS enterprise value using revenue and EBITDA multiples.',
    keywords: ['website valuation', 'business valuation calculator'], tags: ['valuation', 'business'] },
  { id: 'fin-loan-emi-amortization-schedule', name: 'Loan EMI & Amortization Schedule', path: '/finance-math-tools/loan-emi-amortization-schedule', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'schedule',
    desc: 'Calculate monthly loan EMI repayments and view year-by-year principal amortization.',
    keywords: ['emi calculator', 'loan amortization schedule'], tags: ['loan', 'emi'] },
  { id: 'fin-adsense-estimated-revenue-calculator', name: 'AdSense Estimated Revenue Calculator', path: '/finance-math-tools/adsense-estimated-revenue-calculator', category: 'finance-math-tools', icon: 'calculator', engine: 'financeEngine', input: 'numbers', output: 'rpm',
    desc: 'Project monthly advertising earnings based on daily pageviews, CTR, CPC, and RPM.',
    keywords: ['adsense revenue calculator', 'website rpm calculator'], tags: ['adsense', 'revenue'] }
];

export const getToolByPath = (path) => TOOLS.find(t => t.path === path || t.path === `${path}/`);
export const getToolsByCategory = (catId) => TOOLS.filter(t => t.category === catId);
